# Generated by Django 3.1.7 on 2021-03-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20210321_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.category'),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.location'),
        ),
    ]
