# Generated by Django 3.1.7 on 2021-03-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20210321_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
                ('image_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.category')),
                ('image_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pic.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
