# Generated by Django 3.1.7 on 2021-03-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0004_auto_20210321_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
